_BASE_: "Base-CondInst.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 8
  CONDINST:
    MASK_BRANCH:
      SEMANTIC_LOSS_ON: True
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.005
  STEPS: (21600, 28800,)
  MAX_ITER: 31500
OUTPUT_DIR: "output/condinst_MS_R_101_3x_sem_single_scale"
INPUT:
  MIN_SIZE_TRAIN: (720,)
  MAX_SIZE_TRAIN: 1280
  MIN_SIZE_TEST: 720
  MAX_SIZE_TEST: 1280
