_BASE_: "Base-CondInst.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (10800, 14400,)
  MAX_ITER: 15750
INPUT:
  MIN_SIZE_TRAIN: (720,)
  MAX_SIZE_TRAIN: 1280
  MIN_SIZE_TEST: 720
  MAX_SIZE_TEST: 1280
OUTPUT_DIR: "output/condinst_MS_R_50_3x"
