_BASE_: "Base-CondInst.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 8
  CONDINST:
    MASK_BRANCH:
      SEMANTIC_LOSS_ON: True
SOLVER:
  CLIP_GRADIENTS:
    CLIP_TYPE: value
    CLIP_VALUE: 1.0
    ENABLED: True
    NORM_TYPE: 2.0
  IMS_PER_BATCH: 6
  BASE_LR: 0.000375
  STEPS: (288000, 384000,)
  MAX_ITER: 420000
OUTPUT_DIR: "output/condinst_MS_R_101_3x_se_clip"
INPUT:
  MIN_SIZE_TRAIN:
  - 800
  - 832
  - 864
  - 896
  - 928
  - 960
  - 992
  - 1024
  - 1024
  MAX_SIZE_TRAIN: 2048
  MIN_SIZE_TEST: 2048
  MAX_SIZE_TEST: 2048
